# Generated by Django 4.2.4 on 2023-11-03 21:19

import checklist.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('checklist', '0003_alter_sharedchecklist_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.CharField(default=checklist.models.generate_random_token, max_length=64, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('last_edited_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_lists', to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ManyToManyField(related_name='shared_shopping_lists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='shoppingitem',
            name='shopping_lists',
            field=models.ManyToManyField(related_name='shopping_items', to='checklist.shoppinglist'),
        ),
    ]
